Adicionando os trechos restantes sobre testes
gomex/deploy-em-producao pull request #16
Opened 2020-08-26 17:59 UTC by samycici

Incluindo os trechos restantes sobre testes.

2020-09-17 13:06 UTC, gomex requested changes

2020-09-17 13:06 UTC, gomex commented on manuscript/testes_continuous.md
> +Pré-submit é o momento antes de enviar as alterações para o repositório. Nesse momento devemos executar os testes que são mais rápidos e confiáveis, como os testes pequenos que vimos na seção anterio
Seria o caso de falar aqui como normalmente é feito isso? Que são aquelas regras do git, né? Só uma sugestão mesmo.

2020-09-17 13:06 UTC, gomex commented on manuscript/testes_continuous.md
> +Depois que o código é enviado para o repositório, partimos para o processo de integrar esse novo código no código já existente e garantir que tudo continua funcionando, aqui já executamos os testes m
O que vc acha de dizer que isso acontece como um dos primeiro passo do pipeline? Somente pra deixar mais claro mesmo.

2020-09-17 13:06 UTC, gomex commented on manuscript/testes_continuous.md
> +Depois que temos uma versão candidata já publicada em algum ambiente de testes é a hora de executar os testes grandes para validar que os fluxos de negócio estão funcionando de forma integrada com to
O que acha de conceituar a versão candidata antes de dizer o que faz com ela?

2020-09-17 13:06 UTC, gomex commented on manuscript/testes_continuous.md
>  ### Produção
O que acha de falar de deploy em ambientes não prod antes?

2020-10-23 01:37 UTC, samycici commented on manuscript/Book.txt
> +desafios_em_tests.md
corrigido

2020-10-23 01:37 UTC, samycici commented on manuscript/testes_continuous.md
> +Pré-submit é o momento antes de enviar as alterações para o repositório. Nesse momento devemos executar os testes que são mais rápidos e confiáveis, como os testes pequenos que vimos na seção anterio
feito

2020-10-23 01:37 UTC, samycici commented on manuscript/testes_continuous.md
> +Depois que o código é enviado para o repositório, partimos para o processo de integrar esse novo código no código já existente e garantir que tudo continua funcionando, aqui já executamos os testes m
feito

2020-10-23 01:37 UTC, samycici commented on manuscript/testes_continuous.md
> +Depois que temos uma versão candidata já publicada em algum ambiente de testes é a hora de executar os testes grandes para validar que os fluxos de negócio estão funcionando de forma integrada com to
feito

2020-10-23 01:37 UTC, samycici commented on manuscript/testes_continuous.md
>  ### Produção
feito

2020-10-25 14:27 UTC, gomex commented on manuscript/testes_continuous.md
> +
Será que rolaria aqui mostrar algum repositório de exemplo com isso? Seria bacana nesse momento a pessoa ver isso na prática pra entender o processo. O que acha?

2020-10-25 14:29 UTC, gomex requested changes
Eu tenho apenas essa ultima sugestão. Talvez seja exagero, então me diga o que acha. Seria muito bom um exemplo prático pra pessoa que ler de fato entender isso, pois quem nunca pegou isso, talvez seja um pouco distante.

2020-10-25 14:29 UTC, gomex commented on manuscript/testes_continuous.md
> +Pré-submit é o momento antes de enviar as alterações para o repositório. Nesse momento devemos executar os testes que são mais rápidos e confiáveis, como os testes pequenos que vimos na seção anterio
Será que rolaria aqui mostrar algum repositório de exemplo com isso? Seria bacana nesse momento a pessoa ver isso na prática pra entender o processo. O que acha?

2020-10-25 16:49 UTC, samycici commented on manuscript/testes_continuous.md
> +Pré-submit é o momento antes de enviar as alterações para o repositório. Nesse momento devemos executar os testes que são mais rápidos e confiáveis, como os testes pequenos que vimos na seção anterio
pronto, confere por favor.

2020-10-27 15:42 UTC, gomex approved these changes

2020-10-27 15:43 UTC, gomex approved these changes
LGTM

2020-10-27 15:43 UTC, merged